name: Run Ankle Processing Pipeline

on:
  workflow_dispatch:  # 수동 실행 가능
  push:
    paths:
      - 'scripts/**'
      - 'data/dcm/**'
      - 'run_all.sh'

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pydicom opencv-python-headless numpy

      - name: Run pipeline
        run: bash run_all.sh

      - name: Commit results
        run: |
          git config user.name "ankle-bot"
          git config user.email "bot@example.com"
          git add results/curvature.json
          git commit -m "자동 분석 결과 업데이트" || echo "No changes"
          git push
